In [13]:
import pandas as pd
import datetime as dt

# model
from model.model import model_data

# ler parquet
from getdata.get_parquet import get_parquet_silver

In [2]:
# import sys
# # Add the ptdraft folder path to the sys.path list
# sys.path.append('/path/to/ptdraft/')

In [14]:
def main_debito(ano): 

    # generate
    df = pd.DataFrame()

    df = get_parquet_silver(f'extrato_{ano}','debito')

    dfd = model_data(df)

    if dfd is not None:

        dfd["valor_custo"] = dfd["valor_custo"].fillna(0)
        dfd["valor_saldo"] = dfd["valor_saldo"].fillna(0)
        # ... resto do processamento ...
    else:
        print("Erro ao validar dados, DataFrame não foi criado.")    

    now = dt.datetime.now()
    dt_process = dt.datetime.fromtimestamp(dt.datetime.timestamp(now))

    dfd["process_time"] = dt_process #.strftime("%Y-%m-%d %H:%M:%S.%f %z")

    return dfd

In [15]:

dfd = pd.DataFrame()
dfd = main_debito('2026')

TOTAL DE LINHAS (S3): 367 / PATH: s3://medalion-cust/silver/debito/extrato_2026.parquet

dt_custo               object
descricao              object
valor_custo            object
valor_receb            object
valor_saldo            object
data_base      datetime64[ns]
dtype: object

In [16]:
len(dfd)

367

# GERADO LISTAGEM DO CUSTO

In [ ]:
# tipo_docu = 'analytics_pushout_saida'
# parquet_file = 'extract_cust_transform_2026'
# s3_path=f"s3://medalion-cust/silver/{tipo_docu}/{parquet_file}.parquet"
# # generate_parquet_analytics(df, 'pushout_saida', f'extract_cust_transform_{ano}')
# # s3_options={}

# df = pd.read_parquet(s3_path, storage_options={}, engine="pyarrow") 

df = get_parquet_silver(f'extract_cust_transform_2026','analytics_pushout_saida')
df[['descricao','tipo_custo']].to_json("depara_legado.json", orient="records", force_ascii=False, indent=2)
list_depara_legado = df[['descricao','tipo_custo']].values.tolist()
print(f"TOTAL DE LINHAS (S3): {len(df)}", "\n")

TOTAL DE LINHAS (S3): 284 / PATH: s3://medalion-cust/silver/analytics_pushout_saida/extract_cust_transform_2026.parquet

TOTAL DE LINHAS (S3): 284

In [11]:
df.head(10)

,dt_custo,descricao,valor_custo,valor_receb,valor_saldo,data_base,process_time,tipo_custo,week_br,dept_custo,classificacao_custo,area_custo
0,2026-01-02,ELECTRON NSA I POSTO 0201,30.00,-30.00,0.0,2026-01-01,2026-03-10 11:21:32.709882,gasolina,sexta-feira,gasolina,variado,carro
1,2026-01-02,ELECTRON NSA I POSTO 0201,27.58,-27.58,0.0,2026-01-01,2026-03-10 11:21:32.709882,gasolina,sexta-feira,gasolina,variado,carro
2,2026-01-02,ELECTRON LOCALIZA RAC0201,75.84,-75.84,0.0,2026-01-01,2026-03-10 11:21:32.709882,locadora-localiza,sexta-feira,locadora,variado,carro
3,2026-01-02,ELECTRON SHOPPING MET0201,3.00,-3.00,0.0,2026-01-01,2026-03-10 11:21:32.709882,comercio,sexta-feira,comercio,variado,comercio
4,2026-01-02,ELECTRON OGGI SORVETE0201,52.95,-52.95,0.0,2026-01-01,2026-03-10 11:21:32.709882,alimentacao-sorvete,sexta-feira,alimentacao,variado,medio_n1
5,2026-01-02,ELECTRON PAES E DOCES0201,15.00,-15.00,0.0,2026-01-01,2026-03-10 11:21:32.709882,padaria,sexta-feira,padaria,variado,medio_n1
6,2026-01-05,ELECTRON CarlosDiyodi0301,15.00,-15.00,0.0,2026-01-01,2026-03-10 11:21:32.709882,feira-legumes,segunda-feira,feira,variado,medio_n1
7,2026-01-05,ELECTRON GilsonMarque0301,10.00,-10.00,0.0,2026-01-01,2026-03-10 11:21:32.709882,feira,segunda-feira,feira,variado,medio_n1
8,2026-01-05,ELECTRON VALDENICIO D0301,7.00,-7.00,0.0,2026-01-01,2026-03-10 11:21:32.709882,feira,segunda-feira,feira,variado,medio_n1
9,2026-01-05,ELECTRON MP ORIEL 0301,30.00,-30.00,0.0,2026-01-01,2026-03-10 11:21:32.709882,feira-frutas,segunda-feira,feira,variado,medio_n1

# GERADO LISTAGEM CSV DEPARA

# APLICAR LISTAGEM

# DIACONO-IA

In [25]:
df["tipo_custo"]=None

In [26]:
# --> list_diacno_ia
# Filtrar apenas linhas onde tipo_custo está nulo
df_nulo_2 = df[df['tipo_custo'].isnull()].copy()
lista_descricao_df = df_nulo_2["descricao"].drop_duplicates().values.tolist()

In [27]:
lista_descricao_df

['ELECTRON NSA I POSTO 0201',
 'ELECTRON LOCALIZA RAC0201',
 'ELECTRON SHOPPING MET0201',
 'ELECTRON OGGI SORVETE0201',
 'ELECTRON PAES E DOCES0201',
 'ELECTRON CarlosDiyodi0301',
 'ELECTRON GilsonMarque0301',
 'ELECTRON VALDENICIO D0301',
 'ELECTRON MP ORIEL    0301',
 'ELECTRON BANANAS ANAC0301',
 'ELECTRON MP  GILMAR150301',
 'ELECTRON PKF COMERCIO0301',
 'ELECTRON CALDO MANABE0301',
 'ELECTRON FLAMENGO ACA0301',
 'ELECTRON Syscashtycke0301',
 'ELECTRON RS AVILA    0301',
 'ELECTRON FRIGOMUNDO C0301',
 'ELECTRON PONTO DA ESF0301',
 'ELECTRON PADARIA DELI0401',
 'ELECTRON MINI EXTRA-50401',
 'ELECTRON SUPER ADVANC0501',
 'ELECTRON DROGARIA SAO0501',
 'ELECTRON 5M COMERCIO 0501',
 'ELECTRON HORTIFRUTI T0501',
 'ITAU SEG VIDA PF   02/12',
 'PAG BOLETO CONDOMINIO EDIFICIO ALLEGRO',
 'PIX TRANSF EDSON A06/01',
 'ELECTRON MINI EXTRA-50601',
 'PIX QRS PAGUEVELOZ08/01',
 'ELECTRON RS AVILA    0801',
 'ELECTRON FRIGOMUNDO C0901',
 'ELECTRON MINI EXTRA-50901',
 'PIX TRANSF REAL BR09/01',
 'PIX QRS LOCALIZA FL09/01',
 'PIX QRS LOCALIZA  S09/01',
 'DEB AUTOR UNICEF',
 'ELECTRON FRIGOMUNDO C1001',
 'ELECTRON MINI EXTRA-51001',
 'ELECTRON MP ORIEL    1001',
 'ELECTRON MAYO BURGER 1001',
 'ELECTRON RosileneDaSi1001',
 'ELECTRON CarlosDiyodi1001',
 'ELECTRON BarracaDoCun1001',
 'ELECTRON CASSIO ANDRE1001',
 'ELECTRON MP FEIRANTE 1001',
 'ELECTRON PRICILA ELAI1001',
 'ELECTRON MP PKF      1001',
 'ELECTRON MP GILMAR15 1001',
 'ELECTRON RS AVILA    1001',
 'ELECTRON OGGI SORVETE1001',
 'ELECTRON 5M COMERCIO 1001',
 'ELECTRON MARCELO FERR1101',
 'ELECTRON PEDRO ANTONI1101',
 'ELECTRON RR E KK COM 1101',
 'ELECTRON MERCADO EXTR1101',
 'ELECTRON MINI EXTRA-51201',
 'ELECTRON FRIGOMUNDO C1201',
 'SEGURO CARTAO',
 'ELECTRON CARTORIO DE 1301',
 'ELECTRON ACAI E GELIN1301',
 'ELECTRON AdolfoOchsen1401',
 'ELECTRON PONTO DA ESF1601',
 'ELECTRON FRIGOMUNDO C1601',
 'ELECTRON FRIGOMUNDO C1701',
 'ELECTRON OrielPereira1701',
 'ELECTRON RosileneDaSi1701',
 'ELECTRON CarlosDiyodi1701',
 'ELECTRON GILDASIO ALV1701',
 'ELECTRON PKF COMERCIO1701',
 'ELECTRON BANANAS ANAC1701',
 'ELECTRON MP GILMAR15 1701',
 'ELECTRON CALDO MANABE1701',
 'ELECTRON MAYO BURGER 1701',
 "ELECTRON URBANO'S    1701",
 'ELECTRON TRIMAIS II  1701',
 'PIX QRS MULTIDISPLA18/01',
 'PIX TRANSF Ademar 18/01',
 'ELECTRON 5M COMERCIO 1801',
 'ELECTRON OGGI SORVETE1801',
 'ELECTRON SMART BREAK 1801',
 'ELECTRON HORA PARK   1801',
 'FATURA PAGA Itau Uniclas',
 'ELECTRON FRANCLAU AUT2001',
 'ITAU BLACK  6515-7648',
 'DA  CLARO BL/IT 75680788',
 'PIX QRS MULTIDISPLA21/01',
 'ELECTRON PADARIA JD B2101',
 'ELECTRON ParadaExpres2101',
 'ELECTRON LuizaDeFatim2401',
 'ELECTRON PKF COMERCIO2401',
 'ELECTRON WilliamSanto2401',
 'ELECTRON PONTO DA ESF2401',
 'ELECTRON 5M COMERCIO 2501',
 'ELECTRON Shirleydesou2501',
 'ELECTRON PADARIA SOPH2701',
 'ELECTRON ENTREPOSTO E2701',
 'ELECTRON AdolfoOchsen2801',
 'ELECTRON FRIGOMUNDO C2901',
 'ELECTRON OGGI SORVETE2901',
 'ELECTRON PadariaCharm2901',
 'ELECTRON DUNGAS BURGU3001',
 'ELECTRON MP ORIEL    3101',
 'ELECTRON RosileneDaSi3101',
 'ELECTRON MAYO BURGER 3101',
 'ELECTRON CarlosDiyodi3101',
 'ELECTRON BarracaDoCun3101',
 'ELECTRON CASSIO ANDRE3101',
 'ELECTRON FEIRANTES   3101',
 'ELECTRON BANANAS ANAC3101',
 'ELECTRON MP PKF      3101',
 'ELECTRON MP MARQUES  3101',
 'ELECTRON FRIGOMUNDO C3101',
 'ELECTRON MARIAJOSEDOS3101',
 'ELECTRON FEIJAO NOVO 3101',
 'ELECTRON MP BARBEARIA3101',
 'ELECTRON NM PIZZARIA 3101',
 'PIX TRANSF ELIZABE02/02',
 'PIX TRANSF Andre N02/02',
 'PIX TRANSF ANDRE N02/02',
 'PIX QRS DEMERGE BRA03/02',
 'IOF',
 'PIX TRANSF ANDRE N04/02',
 'PIX QRS PAGUEVELOZ04/02',
 'PIX TRANSF Dayane 05/02',
 'PIX TRANSF REAL BR05/02',
 'PIX TRANSF EDSON A05/02',
 'ELECTRON FRIGOMUNDO C0502',
 'ITAU SEG VIDA PF   03/12',
 'JUROS LIMITE DA CONTA',
 'ELECTRON GAROA PAULIS0602',
 'ELECTRON MERCADINHO I0602',
 'ELECTRON KOTAY       0602',
 'ELECTRON OrielPereira0702',
 'ELECTRON FEIRANTES   0702',
 'ELECTRON CASSIO ANDRE0702',
 'ELECTRON PRICILA ELAI0702',
 'ELECTRON PKF COMERCIO0702',
 'ELECTRON MP WMVERDURA0702',
 'ELECTRON MP REALBRASI0702',
 'ELECTRON PADARIA DELI0802',
 'ELECTRON HIP BERGAMIN0802',
 'PAGTO FINANC VEIC 01/48',
 'ELECTRON MP MICHELEBA0902',
 'ELECTRON PADARIA DELI1002',
 'ELECTRON Churrascaria1002',
 'ELECTRON AdolfoOchsen1102',
 'ELECTRON OtavioQuirin1202',
 'PIX TRANSF Ademar 13/02',
 'ELECTRON THE BEST ACA1302',
 'ELECTRON PONTO DA ESF1302',
 'ELECTRON ATACADAO 0601402',
 'ELECTRON AutoPostoAtu1402',
 'ELECTRON ZIG Jump Are1402',
 'ELECTRON MP SAMARCOSD1402',
 'ELECTRON AGUA DE COCO1402',
 'PIX QRS REAL BRASIL14/02',
 'ELECTRON QUITANDA E M1502',
 'ELECTRON MINI EXTRA-51502',
 'ELECTRON FRIGOMUNDO C1502',
 'ELECTRON FDI FERNAO D1502',
 'ELECTRON NSAI POSTO D1602',
 'ELECTRON DROGARIA SAO1602',
 'ELECTRON RP SERVICOS 1702',
 'ELECTRON IvoneteMaria1702',
 'ELECTRON ArenaSantana0703',
 'Agendado',
 'PIX QRS UBER DO BRA03/01',
 'PIX TRANSF IMW 3 R04/01',
 'DA  CLARO CELULAR  68279',
 'PIX QRS UBER DO BRA07/01',
 'PIX TRANSF IMW 3 R11/01',
 'PIX QRS UBER DO BRA11/01',
 'PIX QRS CEA PAY FUN15/01',
 'DA  CLARO CELULAR  64592',
 'DA  ELETROPAULO 11701161',
 'DA  COMGAS 51448254',
 'FINANC IMOBILIARIO 046/360',
 'PIX QRS UBER DO BRA29/01',
 'PIX TRANSF IMW 3 R02/02',
 'PIX QRS ANDRE NASCI02/02',
 'SABESP      3082129325',
 'PIX QRS UBER DO BRA04/02',
 'PIX TRANSF IMW 3 R15/02',
 'PIX QRS CEA PAY FUN17/02',
 'PIX QRS MULTIDISPLA18/02',
 'ELECTRON AdolfoOchsen1802',
 'ELECTRON JULIO BUONO 1902',
 'ELECTRON MP DOGS     2002',
 'ELECTRON 5M COMERCIO 2002',
 'FATURAITAU UNICLASS M',
 'ELECTRON MP REALBRASI2102',
 'ELECTRON MP  ORIEL   2102',
 'ELECTRON OrielPereira2102',
 'ELECTRON MP ORIEL    2102',
 'ELECTRON RosileneDaSi2102',
 'ELECTRON MAYO BURGER 2102',
 'ELECTRON CarlosDiyodi2102',
 'ELECTRON BarracaDoCun2102',
 'ELECTRON CASSIO ANDRE2102',
 'ELECTRON FEIRANTES   2102',
 'ELECTRON VERA C VIEIR2102',
 'ELECTRON PKF COMERCIO2102',
 'ELECTRON KUNIKO KOHAK2102',
 'ELECTRON CALDO MANABE2102',
 'ELECTRON RenanMoraesD2102',
 'ELECTRON SAPECA KIDS 2102',
 'ELECTRON CAMPEA      2102',
 'ELECTRON FRIGOMUNDO C2202',
 'ELECTRON MP REALBRASI2202',
 'ELECTRON PADARIA DELI2202',
 'FINANC IMOBILIARIO 047/360',
 'ELECTRON GALPAO GAUCH2602',
 'ELECTRON MP PADARIAG 2602',
 'ELECTRON OrielPereira2802',
 'ELECTRON MP WMVERDURA2802',
 'ELECTRON GILDASIO ALV2802',
 'ELECTRON BANANAS ANAC2802',
 'ELECTRON MP PKF      2802',
 'ELECTRON ArianaDias  2802',
 'ELECTRON MP ORIEL    2802',
 'ELECTRON LUIZ ANTONIO2802',
 'ELECTRON MP REALBRASI2802',
 'PIX QRS TUNA PAGAME01/03',
 'ELECTRON RS AVILA    0203',
 'PIX TRANSF Ademar 02/03',
 'ELECTRON LUIZ ANTONIO0203',
 'ELECTRON JulianeLimaD0203',
 'ELECTRON MP BARDOGERS0303',
 'ELECTRON MP CHURROSDO0303',
 'PIX TRANSF REAL BR04/03',
 'PIX TRANSF IMW 3 R04/03',
 'ELECTRON MP BARBEARIA0403',
 'ELECTRON LUIZ ANTONIO0503',
 'ITAU SEG VIDA PF   04/12',
 'ELECTRON MP IFECO    0603',
 'PIX TRANSF EDSON A06/03',
 'ELECTRON MARCELO PINH0703',
 'ELECTRON MAYO BURGER 0703',
 'ELECTRON CarlosDiyodi0703',
 'ELECTRON CASSIO ANDRE0703',
 'ELECTRON MP FEIRANTE 0703',
 'ELECTRON LuizaDeFatim0703',
 'ELECTRON MP PKF      0703',
 'ELECTRON MP ORIEL    0703',
 'ELECTRON LUIZ ANTONIO0703',
 'ELECTRON OGGI SORVETE0703',
 'PIX TRANSF VERA LU07/03',
 'ELECTRON T E G FOOD R0803',
 'PAGTO FINANC VEIC 02/48',
 'ELECTRON ARIZONA PAES0903']

In [29]:
from diacono_categ.agent import classificar_com_ia
from dotenv import load_dotenv


load_dotenv()
#lista=['ELECTRON MINI EXTRA-51502','ELECTRON FRIGOMUNDO C1502','ELECTRON FDI FERNAO D1502','ELECTRON NSAI POSTO D1602','ELECTRON DROGARIA SAO1602','ELECTRON RP SERVICOS 1702','ELECTRON RP SERVICOS 1702','ELECTRON IvoneteMaria1702']
categoria=[classificar_com_ia(l) for l in lista_descricao_df]

# with open('saida.json', 'r', encoding='utf-8') as f:
# dados = json.load(categoria)
list_diacno_ia = [[ item['original'], item['categoria']] for item in categoria]

In [30]:
list_diacno_ia

[['ELECTRON NSA I POSTO 0201', 'gasolina'],
 ['ELECTRON LOCALIZA RAC0201', 'transporte_pub'],
 ['ELECTRON SHOPPING MET0201', 'shopping'],
 ['ELECTRON OGGI SORVETE0201', 'sorvete'],
 ['ELECTRON PAES E DOCES0201', 'alimentacao'],
 ['ELECTRON CarlosDiyodi0301', 'comercio'],
 ['ELECTRON GilsonMarque0301', 'vazio'],
 ['ELECTRON VALDENICIO D0301', 'vazio'],
 ['ELECTRON MP ORIEL    0301', ''],
 ['ELECTRON BANANAS ANAC0301', 'mercado'],
 ['ELECTRON MP  GILMAR150301', ''],
 ['ELECTRON PKF COMERCIO0301', 'comercio'],
 ['ELECTRON CALDO MANABE0301', 'alimentacao'],
 ['ELECTRON FLAMENGO ACA0301', 'futebol_amigos'],
 ['ELECTRON Syscashtycke0301', ''],
 ['ELECTRON RS AVILA    0301', 'comercio'],
 ['ELECTRON FRIGOMUNDO C0301', 'alimentacao'],
 ['ELECTRON PONTO DA ESF0301', 'alimentaçao'],
 ['ELECTRON PADARIA DELI0401', 'padaria'],
 ['ELECTRON MINI EXTRA-50401', 'mercado'],
 ['ELECTRON SUPER ADVANC0501', ''],
 ['ELECTRON DROGARIA SAO0501', 'farmacia'],
 ['ELECTRON 5M COMERCIO 0501', 'comercio'],
 ['ELECTRON HORTIFRUTI T0501', 'mercado'],
 ['ITAU SEG VIDA PF   02/12', 'seguro'],
 ['PAG BOLETO CONDOMINIO EDIFICIO ALLEGRO', 'boleto'],
 ['PIX TRANSF EDSON A06/01', 'banco'],
 ['ELECTRON MINI EXTRA-50601', 'mercado'],
 ['PIX QRS PAGUEVELOZ08/01', 'banco'],
 ['ELECTRON RS AVILA    0801', 'comercio'],
 ['ELECTRON FRIGOMUNDO C0901', 'alimentacao'],
 ['ELECTRON MINI EXTRA-50901', 'mercado'],
 ['PIX TRANSF REAL BR09/01', 'banco'],
 ['PIX QRS LOCALIZA FL09/01', ''],
 ['PIX QRS LOCALIZA  S09/01', 'banco'],
 ['DEB AUTOR UNICEF', ''],
 ['ELECTRON FRIGOMUNDO C1001', 'mercado'],
 ['ELECTRON MINI EXTRA-51001', 'mercado'],
 ['ELECTRON MP ORIEL    1001', ''],
 ['ELECTRON MAYO BURGER 1001', 'alimentacao'],
 ['ELECTRON RosileneDaSi1001', 'vazio'],
 ['ELECTRON CarlosDiyodi1001', 'comercio'],
 ['ELECTRON BarracaDoCun1001', 'alimentacao'],
 ['ELECTRON CASSIO ANDRE1001', 'vazio'],
 ['ELECTRON MP FEIRANTE 1001', 'feira'],
 ['ELECTRON PRICILA ELAI1001', 'vazio'],
 ['ELECTRON MP PKF      1001', ''],
 ['ELECTRON MP GILMAR15 1001', 'comercio'],
 ['ELECTRON RS AVILA    1001', 'comercio'],
 ['ELECTRON OGGI SORVETE1001', 'sorvete'],
 ['ELECTRON 5M COMERCIO 1001', 'comercio'],
 ['ELECTRON MARCELO FERR1101', 'vazio'],
 ['ELECTRON PEDRO ANTONI1101', 'vazio'],
 ['ELECTRON RR E KK COM 1101', 'comercio'],
 ['ELECTRON MERCADO EXTR1101', 'mercado'],
 ['ELECTRON MINI EXTRA-51201', 'mercado'],
 ['ELECTRON FRIGOMUNDO C1201', 'alimentacao'],
 ['SEGURO CARTAO', 'seguro'],
 ['ELECTRON CARTORIO DE 1301', ''],
 ['ELECTRON ACAI E GELIN1301', 'alimentacao'],
 ['ELECTRON AdolfoOchsen1401', 'vazio'],
 ['ELECTRON PONTO DA ESF1601', 'alimentaçao'],
 ['ELECTRON FRIGOMUNDO C1601', 'mercado'],
 ['ELECTRON FRIGOMUNDO C1701', 'mercado'],
 ['ELECTRON OrielPereira1701', ''],
 ['ELECTRON RosileneDaSi1701', 'vazio'],
 ['ELECTRON CarlosDiyodi1701', 'comercio'],
 ['ELECTRON GILDASIO ALV1701', 'vazio'],
 ['ELECTRON PKF COMERCIO1701', 'comercio'],
 ['ELECTRON BANANAS ANAC1701', 'mercado'],
 ['ELECTRON MP GILMAR15 1701', ''],
 ['ELECTRON CALDO MANABE1701', 'alimentacao'],
 ['ELECTRON MAYO BURGER 1701', 'alimentacao'],
 ["ELECTRON URBANO'S    1701", 'transporte_pub'],
 ['ELECTRON TRIMAIS II  1701', ''],
 ['PIX QRS MULTIDISPLA18/01', ''],
 ['PIX TRANSF Ademar 18/01', ''],
 ['ELECTRON 5M COMERCIO 1801', 'comercio'],
 ['ELECTRON OGGI SORVETE1801', 'sorvete'],
 ['ELECTRON SMART BREAK 1801', 'alimentacao'],
 ['ELECTRON HORA PARK   1801', 'transporte_pub'],
 ['FATURA PAGA Itau Uniclas', 'banco'],
 ['ELECTRON FRANCLAU AUT2001', 'comercio'],
 ['ITAU BLACK  6515-7648', 'banco'],
 ['DA  CLARO BL/IT 75680788', 'claro'],
 ['PIX QRS MULTIDISPLA21/01', ''],
 ['ELECTRON PADARIA JD B2101', 'padaria'],
 ['ELECTRON ParadaExpres2101', 'transporte_pub'],
 ['ELECTRON LuizaDeFatim2401', 'vazio'],
 ['ELECTRON PKF COMERCIO2401', 'comercio'],
 ['ELECTRON WilliamSanto2401', 'vazio'],
 ['ELECTRON PONTO DA ESF2401', 'alimentacao'],
 ['ELECTRON 5M COMERCIO 2501', 'comercio'],
 ['ELECTRON Shirleydesou2501', 'vazio'],
 ['ELECTRON PADARIA SOPH2701', 'padaria'],
 ['ELECTRON ENTREPOSTO E2701', 'comercio'],
 ['ELECTRON AdolfoOchsen2801', 'vazio'],
 ['ELECTRON FRIGOMUNDO C2901', 'alimentacao'],
 ['ELECTRON OGGI SORVETE2901', 'sorvete'],
 ['ELECTRON PadariaCharm2901', 'padaria'],
 ['ELECTRON DUNGAS BURGU3001', 'alimentacao'],
 ['ELECTRON MP ORIEL    3101', 'comercio'],
 ['ELECTRON RosileneDaSi3101', 'vazio'],
 ['ELECTRON MAYO BURGER 3101', 'alimentacao'],
 ['ELECTRON CarlosDiyodi3101', 'comercio'],
 ['ELECTRON BarracaDoCun3101', 'alimentacao'],
 ['ELECTRON CASSIO ANDRE3101', 'vazio'],
 ['ELECTRON FEIRANTES   3101', 'feira'],
 ['ELECTRON BANANAS ANAC3101', 'mercado'],
 ['ELECTRON MP PKF      3101', ''],
 ['ELECTRON MP MARQUES  3101', 'comercio'],
 ['ELECTRON FRIGOMUNDO C3101', 'mercado'],
 ['ELECTRON MARIAJOSEDOS3101', 'vazio'],
 ['ELECTRON FEIJAO NOVO 3101', 'mercado'],
 ['ELECTRON MP BARBEARIA3101', 'cabelereiro'],
 ['ELECTRON NM PIZZARIA 3101', 'alimentacao'],
 ['PIX TRANSF ELIZABE02/02', 'banco'],
 ['PIX TRANSF Andre N02/02', 'banco'],
 ['PIX TRANSF ANDRE N02/02', 'banco'],
 ['PIX QRS DEMERGE BRA03/02', 'banco'],
 ['IOF', ''],
 ['PIX TRANSF ANDRE N04/02', 'banco'],
 ['PIX QRS PAGUEVELOZ04/02', 'banco'],
 ['PIX TRANSF Dayane 05/02', ''],
 ['PIX TRANSF REAL BR05/02', 'banco'],
 ['PIX TRANSF EDSON A05/02', 'banco'],
 ['ELECTRON FRIGOMUNDO C0502', 'mercado'],
 ['ITAU SEG VIDA PF   03/12', 'seguro'],
 ['JUROS LIMITE DA CONTA', 'juros'],
 ['ELECTRON GAROA PAULIS0602', ''],
 ['ELECTRON MERCADINHO I0602', 'mercado'],
 ['ELECTRON KOTAY       0602', 'comercio'],
 ['ELECTRON OrielPereira0702', 'vazio'],
 ['ELECTRON FEIRANTES   0702', 'feira'],
 ['ELECTRON CASSIO ANDRE0702', 'vazio'],
 ['ELECTRON PRICILA ELAI0702', 'vazio'],
 ['ELECTRON PKF COMERCIO0702', 'comercio'],
 ['ELECTRON MP WMVERDURA0702', 'feira'],
 ['ELECTRON MP REALBRASI0702', 'comercio'],
 ['ELECTRON PADARIA DELI0802', 'padaria'],
 ['ELECTRON HIP BERGAMIN0802', 'comercio'],
 ['PAGTO FINANC VEIC 01/48', 'financiamento_carro'],
 ['ELECTRON MP MICHELEBA0902', 'michelle'],
 ['ELECTRON PADARIA DELI1002', 'padaria'],
 ['ELECTRON Churrascaria1002', 'alimentacao'],
 ['ELECTRON AdolfoOchsen1102', ''],
 ['ELECTRON OtavioQuirin1202', ''],
 ['PIX TRANSF Ademar 13/02', ''],
 ['ELECTRON THE BEST ACA1302', 'alimentacao'],
 ['ELECTRON PONTO DA ESF1302', 'alimentacao'],
 ['ELECTRON ATACADAO 0601402', 'mercado'],
 ['ELECTRON AutoPostoAtu1402', 'gasolina'],
 ['ELECTRON ZIG Jump Are1402', ''],
 ['ELECTRON MP SAMARCOSD1402', ''],
 ['ELECTRON AGUA DE COCO1402', 'alimentacao'],
 ['PIX QRS REAL BRASIL14/02', 'banco'],
 ['ELECTRON QUITANDA E M1502', 'mercado'],
 ['ELECTRON MINI EXTRA-51502', 'mercado'],
 ['ELECTRON FRIGOMUNDO C1502', 'alimentacao'],
 ['ELECTRON FDI FERNAO D1502', 'posto de gasolina'],
 ['ELECTRON NSAI POSTO D1602', 'gasolina'],
 ['ELECTRON DROGARIA SAO1602', 'farmacia'],
 ['ELECTRON RP SERVICOS 1702', 'comercio'],
 ['ELECTRON IvoneteMaria1702', 'vazio'],
 ['ELECTRON ArenaSantana0703', 'comercio'],
 ['Agendado', 'vazio'],
 ['PIX QRS UBER DO BRA03/01', 'uber'],
 ['PIX TRANSF IMW 3 R04/01', 'igreja'],
 ['DA  CLARO CELULAR  68279', 'claro'],
 ['PIX QRS UBER DO BRA07/01', 'uber'],
 ['PIX TRANSF IMW 3 R11/01', 'igreja'],
 ['PIX QRS UBER DO BRA11/01', 'uber'],
 ['PIX QRS CEA PAY FUN15/01', 'cea'],
 ['DA  CLARO CELULAR  64592', 'claro'],
 ['DA  ELETROPAULO 11701161', 'luz'],
 ['DA  COMGAS 51448254', 'gas'],
 ['FINANC IMOBILIARIO 046/360', 'financiamento'],
 ['PIX QRS UBER DO BRA29/01', 'uber'],
 ['PIX TRANSF IMW 3 R02/02', 'igreja'],
 ['PIX QRS ANDRE NASCI02/02', ''],
 ['SABESP      3082129325', 'agua'],
 ['PIX QRS UBER DO BRA04/02', 'uber'],
 ['PIX TRANSF IMW 3 R15/02', 'igreja'],
 ['PIX QRS CEA PAY FUN17/02', 'cea'],
 ['PIX QRS MULTIDISPLA18/02', ''],
 ['ELECTRON AdolfoOchsen1802', ''],
 ['ELECTRON JULIO BUONO 1902', ''],
 ['ELECTRON MP DOGS     2002', 'alimentacao'],
 ['ELECTRON 5M COMERCIO 2002', 'comercio'],
 ['FATURAITAU UNICLASS M', 'banco'],
 ['ELECTRON MP REALBRASI2102', 'comercio'],
 ['ELECTRON MP  ORIEL   2102', ''],
 ['ELECTRON OrielPereira2102', ''],
 ['ELECTRON MP ORIEL    2102', ''],
 ['ELECTRON RosileneDaSi2102', 'vazio'],
 ['ELECTRON MAYO BURGER 2102', 'alimentacao'],
 ['ELECTRON CarlosDiyodi2102', 'comercio'],
 ['ELECTRON BarracaDoCun2102', 'alimentacao'],
 ['ELECTRON CASSIO ANDRE2102', 'vazio'],
 ['ELECTRON FEIRANTES   2102', 'feira'],
 ['ELECTRON VERA C VIEIR2102', 'vazio'],
 ['ELECTRON PKF COMERCIO2102', 'comercio'],
 ['ELECTRON KUNIKO KOHAK2102', ''],
 ['ELECTRON CALDO MANABE2102', 'alimentacao'],
 ['ELECTRON RenanMoraesD2102', 'vazio'],
 ['ELECTRON SAPECA KIDS 2102', 'escola_futebol'],
 ['ELECTRON CAMPEA      2102', 'futebol_amigos'],
 ['ELECTRON FRIGOMUNDO C2202', 'mercado'],
 ['ELECTRON MP REALBRASI2202', 'comercio'],
 ['ELECTRON PADARIA DELI2202', 'padaria'],
 ['FINANC IMOBILIARIO 047/360', 'financiamento'],
 ['ELECTRON GALPAO GAUCH2602', 'alimentacao'],
 ['ELECTRON MP PADARIAG 2602', 'padaria'],
 ['ELECTRON OrielPereira2802', ''],
 ['ELECTRON MP WMVERDURA2802', 'feira'],
 ['ELECTRON GILDASIO ALV2802', 'vazio'],
 ['ELECTRON BANANAS ANAC2802', 'mercado'],
 ['ELECTRON MP PKF      2802', ''],
 ['ELECTRON ArianaDias  2802', ''],
 ['ELECTRON MP ORIEL    2802', ''],
 ['ELECTRON LUIZ ANTONIO2802', 'vazio'],
 ['ELECTRON MP REALBRASI2802', 'comercio'],
 ['PIX QRS TUNA PAGAME01/03', ''],
 ['ELECTRON RS AVILA    0203', 'comercio'],
 ['PIX TRANSF Ademar 02/03', 'banco'],
 ['ELECTRON LUIZ ANTONIO0203', 'vazio'],
 ['ELECTRON JulianeLimaD0203', 'vazio'],
 ['ELECTRON MP BARDOGERS0303', 'comercio'],
 ['ELECTRON MP CHURROSDO0303', 'alimentacao'],
 ['PIX TRANSF REAL BR04/03', 'banco'],
 ['PIX TRANSF IMW 3 R04/03', 'igreja'],
 ['ELECTRON MP BARBEARIA0403', 'cabelereiro'],
 ['ELECTRON LUIZ ANTONIO0503', 'vazio'],
 ['ITAU SEG VIDA PF   04/12', 'seguro'],
 ['ELECTRON MP IFECO    0603', ''],
 ['PIX TRANSF EDSON A06/03', 'banco'],
 ['ELECTRON MARCELO PINH0703', 'vazio'],
 ['ELECTRON MAYO BURGER 0703', 'alimentacao'],
 ['ELECTRON CarlosDiyodi0703', 'comercio'],
 ['ELECTRON CASSIO ANDRE0703', 'vazio'],
 ['ELECTRON MP FEIRANTE 0703', 'feira'],
 ['ELECTRON LuizaDeFatim0703', ''],
 ['ELECTRON MP PKF      0703', ''],
 ['ELECTRON MP ORIEL    0703', ''],
 ['ELECTRON LUIZ ANTONIO0703', 'vazio'],
 ['ELECTRON OGGI SORVETE0703', 'sorvete'],
 ['PIX TRANSF VERA LU07/03', 'vazio'],
 ['ELECTRON T E G FOOD R0803', 'alimentacao'],
 ['PAGTO FINANC VEIC 02/48', 'financiamento_carro'],
 ['ELECTRON ARIZONA PAES0903', 'alimentacao']]

In [31]:
df["tipo_custo"] = df.apply(lambda x: next((y[1] for y in list_diacno_ia if y[0] in x["descricao"]), None), axis=1)

In [32]:
df[df['tipo_custo'].isnull()]

Empty DataFrame
Columns: [dt_custo, descricao, valor_custo, valor_receb, valor_saldo, data_base, process_time, tipo_custo, week_br, dept_custo, classificacao_custo, area_custo]
Index: []

# unir dataframes

In [33]:
df

,dt_custo,descricao,valor_custo,valor_receb,valor_saldo,data_base,process_time,tipo_custo,week_br,dept_custo,classificacao_custo,area_custo
0,2026-01-02,ELECTRON NSA I POSTO 0201,30.00,-30.00,0.0,2026-01-01,2026-03-25 17:38:32.030185,gasolina,sexta-feira,gasolina,variado,carro
1,2026-01-02,ELECTRON NSA I POSTO 0201,27.58,-27.58,0.0,2026-01-01,2026-03-25 17:38:32.030185,gasolina,sexta-feira,gasolina,variado,carro
2,2026-01-02,ELECTRON LOCALIZA RAC0201,75.84,-75.84,0.0,2026-01-01,2026-03-25 17:38:32.030185,transporte_pub,sexta-feira,locadora,variado,carro
3,2026-01-02,ELECTRON SHOPPING MET0201,3.00,-3.00,0.0,2026-01-01,2026-03-25 17:38:32.030185,shopping,sexta-feira,comercio,variado,comercio
4,2026-01-02,ELECTRON OGGI SORVETE0201,52.95,-52.95,0.0,2026-01-01,2026-03-25 17:38:32.030185,sorvete,sexta-feira,alimentacao,variado,medio_n1
...,...,...,...,...,...,...,...,...,...,...,...,...
279,2026-03-09,PIX TRANSF VERA LU07/03,20.00,-20.00,0.0,2026-03-01,2026-03-25 17:38:32.030185,vazio,segunda-feira,pessoal,variado,baixo
280,2026-03-09,ELECTRON T E G FOOD R0803,247.50,-247.50,0.0,2026-03-01,2026-03-25 17:38:32.030185,alimentacao,segunda-feira,alimentacao,variado,medio_n1
281,2026-03-09,PAGTO FINANC VEIC 02/48,2336.17,-2336.17,0.0,2026-03-01,2026-03-25 17:38:32.030185,financiamento_carro,segunda-feira,financiamento_carro,variado,baixo
282,2026-03-09,ELECTRON ARIZONA PAES0903,40.25,-40.25,0.0,2026-03-01,2026-03-25 17:38:32.030185,alimentacao,segunda-feira,alimentacao,variado,medio_n1
283,2026-03-16,DA CLARO CELULAR 64592,160.24,-160.24,0.0,2026-03-01,2026-03-25 17:38:32.030185,claro,segunda-feira,claro,fixo,medio